[project]
name = "industry-data-in"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bse @ git+https://github.com/eggmasonvalue/BseIndiaApi.git",
    "nse @ git+https://github.com/eggmasonvalue/NseIndiaApi.git",
    "tenacity>=8.2.0",
    "httpx[http2]>=0.25.0",
]
